import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "styles/Home.module.scss";
import { Header, Heading, Shapes } from "components";

const Home: NextPage = () => {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header
          title="SHTFI"
          subTitle="Stop Helping The Finance Industry"
          logo="/assets/icons/shtfi-bg.svg"
          logoAlt="SHTFI logo"
        />
        <div className={styles.intro_section}>
          <Shapes background={true} />
          <Heading text="We're Shit and We Know We Are" level={2} />
          <p>
            Nulla aliqua et Lorem ullamco cillum sunt proident. Occaecat labore
            ipsum nisi fugiat sint ipsum dolore nostrud nostrud eiusmod aliquip.
            Duis magna ea dolor sunt irure adipisicing ea duis. Sunt elit est
            fugiat proident occaecat. Et laboris labore ea anim fugiat
            exercitation irure dolore veniam.
          </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
