import type { NextPage } from "next";
import Head from "next/head";
import {
  Button,
  Card,
  Header,
  Heading,
  Slider,
  Shapes,
  TextIcon,
} from "components";
import styled from "styled-components";

const Home: NextPage = () => {
  return (
    <StyledWrapper>
      {/* Head section */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledMain>
        {/* Header section */}
        <Header
          title="SHTFI"
          subTitle="Stop Helping The Finance Industry"
          logo="/assets/icons/shtfi-bg.svg"
          logoAlt="SHTFI logo"
        />
        {/* Intro section */}
        <StyledIntroSection>
          <Shapes background={true} />
          <Heading text="We're Shit and We Know We Are" level={2} />
          <p>
            Nulla aliqua et Lorem ullamco cillum sunt proident. Occaecat labore
            ipsum nisi fugiat sint ipsum dolore nostrud nostrud eiusmod aliquip.
            Duis magna ea dolor sunt irure adipisicing ea duis. Sunt elit est
            fugiat proident occaecat. Et laboris labore ea anim fugiat
            exercitation irure dolore veniam.
          </p>
        </StyledIntroSection>
        {/* Card section */}
        <StyledCardSection>
          <Card>
            <Shapes
              background={false}
              size="tiny"
              style={{ margin: "calc(var(--large-space) * 2) auto" }}
            />
            <StyledCardContent>
              <Heading level={3} text="Something" style={{ marginTop: 0 }} />
              <p>
                Minim do sit exercitation ut est irure amet aute sint id ea sunt
                sint. Enim et elit exercitation officia id aliquip magna.
              </p>
              <Button onClick={() => console.log("click")}>CTA</Button>
            </StyledCardContent>
          </Card>
        </StyledCardSection>
        {/* Slider section */}
        <StyledSliderSection>
          <Slider>
            <div>
              <Heading level={2} text="SHTFI all day" />
              <TextIcon
                heading="We're the SHTFI"
                copy="Shitty shit shtfi defi decentralised, crypto, blockchain, dao something something elon musk."
                icon="people-carry"
              />
            </div>
            <div>
              <Heading level={2} text="SHTFI all day" />
              <TextIcon
                heading="We're the SHTFI 2"
                copy="Shitty shit shtfi defi decentralised, crypto, blockchain, dao something something elon musk."
                icon="people-carry"
              />
            </div>
          </Slider>
        </StyledSliderSection>
      </StyledMain>
    </StyledWrapper>
  );
};

const StyledWrapper = styled.div`
  flex-direction: column;
  display: flex;
`;
const StyledMain = styled.main``;
const StyledIntroSection = styled.section`
  position: relative;
  min-width: 250px;
  min-height: 250px;
  padding: 0 var(--large-space);
`;
const StyledCardSection = styled.section`
  padding: calc(var(--large-space) * 6) 0;
  position: relative;
  &::after {
    width: 100%;
    height: 50%;
    border-radius: 0 0 calc(var(--radius-large) * 2)
      calc(var(--radius-large) * 2);
    background-color: var(--blue);
    position: absolute;
    bottom: 0;
    content: "";
    z-index: -1;
  }
`;
const StyledCardContent = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: var(--large-space);
  > h3 {
    text-align: center;
    font-size: var(--head-font);
  }
`;
const StyledSliderSection = styled.section`
  padding: calc(var(--large-space) * 6) 0;
`;
export default Home;
